<a href="https://colab.research.google.com/github/allensiu0217/88BearHelloBull/blob/main/%E7%86%8A%E5%8E%BB%E7%89%9B%E4%BE%86_%E7%AC%AC%E4%B8%80%E6%99%82%E9%96%93%E6%8D%89%E5%BA%95.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 安裝必備的金融指標套件 (每次開啟 Colab 只需執行一次)
!pip install pandas_ta -q
print("✅ pandas_ta 套件安裝完成！")

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.5/79.5 kB 3.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.0/62.0 kB 3.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 240.3/240.3 kB 10.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.9/3.9 MB 58.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.5/16.5 MB 50.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 75.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.4/42.4 MB 21.1 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 3.0.1 which is incompatible.
bqplot 0.12.45 requires pandas<3.0.0,>=1.0.0, but you have pandas 3.0.1 which is incompatible.
gradio 5.50.0 requires pandas<3.0,>=1.0, but you have pandas 3.0.1 which is incompatible.
db-dtypes 1.5.0 requires pandas<3.0.0,>=1.5.3, but you have pandas 3.0.1 which is incompatible.
tensorflow 2.19.0 requires numpy<2.2.0,>=1.26.0, but you have numpy 2.2.6 which is incompatible.
✅ pandas_ta 套件安裝完成！

In [ ]:
# 安裝 pandas_ta 技術分析套件
!pip install pandas_ta -q

import yfinance as yf
import pandas as pd
import pandas_ta as ta
import numpy as np
import time
from datetime import datetime, timedelta

print("✅ 套件安裝與載入完成！")

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.5/79.5 kB 2.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.0/62.0 kB 4.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 240.3/240.3 kB 11.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.9/3.9 MB 67.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.5/16.5 MB 76.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 85.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.4/42.4 MB 20.4 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 3.0.1 which is incompatible.
db-dtypes 1.5.0 requires pandas<3.0.0,>=1.5.3, but you have pandas 3.0.1 which is incompatible.
tensorflow 2.19.0 requires numpy<2.2.0,>=1.26.0, but you have numpy 2.2.6 which is incompatible.
gradio 5.50.0 requires pandas<3.0,>=1.0, but you have pandas 3.0.1 which is incompatible.
bqplot 0.12.45 requires pandas<3.0.0,>=1.0.0, but you have pandas 3.0.1 which is incompatible.
✅ 套件安裝與載入完成！

In [3]:
# ========== 熊去牛來：全球跨市場實戰狙擊雷達 (精準錨定訊號日底線止蝕) ==========
!pip install pandas_ta -q
import yfinance as yf
import pandas as pd
import pandas_ta as ta
import numpy as np
import time
import sys
from datetime import datetime

# 👉 全球多資產監控清單
market_watch_lists = {
    "🇺🇸 美股與加密貨幣": [
        "AMD", "AMZN", "ARKG", "ARKK", "ARKX", "ARM", "ASTS", "ASX", "AVGO", "BABA", "BE",
        "AES", "AGX", "ALGN", "AMKR", "CAT", "CAVA", "DECK", "EME", "FIX", "FLEX", "MAR", "MRNA",
        "BLSH", "BTC-USD", "BULL", "BWXT", "CCJ", "CIEN", "COHR", "COIN", "CRWD", "CRWV",
        "DELL", "ENPH", "ESLT", "ETN", "FCX", "FUTU", "GEV", "GOOGL", "HOOD", "HSAI",
        "IBKR", "IONQ", "IREN", "ISRG", "JOBY", "KC", "KWEB", "KTOS", "LEU", "LITE", "MP",
        "MRVL", "MSFT", "MU", "NBIS", "NEM", "NET", "NVDA", "NXT", "ONDS", "ORCL", "OSCR",
        "OXY", "PANW", "PLTR", "RDDT", "RDW", "RKLB", "SATS", "SCCO", "SEDG", "SMCI",
        "SNPS", "SOFI", "STX", "SYM", "TEM", "TER", "TSLA", "TSM", "TSEM", "TTMI", "TXN",
        "VRT", "WDC", "WRD"
    ],
    "🇭🇰 香港股市": [
        "2722.HK", "2038.HK", "0902.HK", "0968.HK", "2727.HK", "0390.HK", "1157.HK", "1133.HK",
        "1428.HK", "1378.HK", "2208.HK", "9698.HK", "2026.HK", "2616.HK", "0981.HK", "3339.HK",
        "1729.HK", "1651.HK", "1050.HK", "9626.HK", "1286.HK", "2359.HK", "2252.HK", "2276.HK",
        "1772.HK", "9880.HK", "1057.HK", "9888.HK", "1816.HK", "6088.HK", "3750.HK", "9988.HK",
        "0700.HK", "1024.HK", "1801.HK", "2202.HK", "1918.HK", "2689.HK", "1579.HK", "1070.HK", "0388.HK"
    ],
    "🇯🇵 日本股市": [
        "8001.T", "8002.T", "8031.T", "8053.T", "8058.T", "285A.T"
    ]
}

watch_list = [sym for market in market_watch_lists.values() for sym in market]

print(f"🚀 啟動【全球熊去牛來】實戰狙擊雷達 (嚴格錨定訊號日底線)...\n")
scan_results = []
total_stocks = len(watch_list)
processed = 0

for sym in watch_list:
    processed += 1
    try:
        df = yf.Ticker(sym).history(period="6mo")
        if len(df) < 50: continue

        macd = df.ta.macd()
        df['MACD'] = macd.iloc[:, 0]
        df['MACD_Signal'] = macd.iloc[:, 2]
        # 定義：熊去牛來訊號發出
        df['Bear_Bull_Signal'] = (df['MACD'] > df['MACD_Signal']) & (df['MACD'].shift(1) <= df['MACD_Signal'].shift(1)) & (df['MACD'] < 0)

        status = "NONE"
        signal_idx, signal_high, rolling_high = -1, np.nan, np.nan

        # 👉 核心變數升級：明確區分「訊號日低點」與「買入日價格」
        signal_day_low = np.nan
        entry_price = np.nan
        entry_idx = -1
        entry_date = None

        for i in range(1, len(df)):
            current_date = df.index[i]
            current_close = df['Close'].iloc[i]
            current_open = df['Open'].iloc[i]
            current_high = df['High'].iloc[i]

            is_signal = df['Bear_Bull_Signal'].iloc[i]

            if status == "NONE":
                if is_signal:
                    status = "WAIT_CONFIRMATION"
                    signal_idx = i
                    signal_high = current_high
                    rolling_high = current_high
                    # 💡 關鍵鎖定：在這裡記錄「發出熊去牛來訊號日」的最低點！
                    signal_day_low = df['Low'].iloc[i]

            elif status == "WAIT_CONFIRMATION":
                days_passed = i - signal_idx
                if days_passed > 10:
                    status = "NONE"; continue

                triggered = False
                # 買入觸發判定 (突破)
                if days_passed == 1 and (current_close > current_open) and current_close > signal_high: triggered = True
                elif days_passed > 1 and current_close > rolling_high: triggered = True

                if triggered:
                    # 記錄「買入觸發日」的價格與時間，但不改變 signal_day_low
                    entry_price, entry_date, entry_idx = current_close, current_date, i
                    status = "HOLDING"
                else:
                    if current_high > rolling_high: rolling_high = current_high

            elif status == "HOLDING":
                # 💡 關鍵止蝕：以「每日收盤價 (current_close)」是否跌破「訊號日最低點 (signal_day_low)」來判定
                if current_close < signal_day_low:
                    status = "NONE"

        # ==========================================
        # 🎯 雷達最後判定 (當下最新一日狀態)
        # ==========================================
        last_idx = len(df) - 1
        current_close = df['Close'].iloc[-1]

        if status == "HOLDING":
            days_since_entry = last_idx - entry_idx

            if days_since_entry <= 5:
                price_diff_pct = abs(current_close - entry_price) / entry_price * 100

                if price_diff_pct <= 5.0:
                    # 止蝕風險計算：基於「現價」與「訊號日最低點」的距離
                    sl_risk_pct = (current_close - signal_day_low) / current_close * 100

                    market_label = "🇺🇸 美股/加密貨幣"
                    if ".HK" in sym: market_label = "🇭🇰 港股"
                    elif ".T" in sym: market_label = "🇯🇵 日股"

                    scan_results.append({
                        "市場": market_label,
                        "標的": sym,
                        "訊號觸發日": entry_date.strftime('%Y-%m-%d'),
                        "已過天數": days_since_entry,
                        "最新收盤價": round(current_close, 2),
                        "買入訊號價": round(entry_price, 2),
                        "現價偏離度(%)": f"{round((current_close - entry_price) / entry_price * 100, 2)}%",
                        "🔴 訊號日止蝕價": round(signal_day_low, 2), # 名稱加上「訊號日」以示絕對清晰
                        "🛡️ 距止蝕風險(%)": f"{round(sl_risk_pct, 2)}%"
                    })

        sys.stdout.write(f"\r⏳ 雷達全球掃描進度: [{processed}/{total_stocks}] 處理中: {sym}" + " "*15)
        sys.stdout.flush()
        time.sleep(0.05)
    except Exception as e: pass

# ========== 印出雷達狙擊報表 ==========
print("\n\n" + "="*90)
print("🎯 【熊去牛來：全球跨市場實戰狙擊清單】")
print("過濾防線：[收市跌穿訊號日低點] 判定出局 | 買入 <= 5天 | 偏離 <= 5%")

if len(scan_results) > 0:
    res_df = pd.DataFrame(scan_results)
    res_df = res_df.sort_values(by='🛡️ 距止蝕風險(%)', key=lambda col: col.str.replace('%', '').astype(float)).reset_index(drop=True)
    display(res_df)
    print("\n💡 操盤建議：這份名單中的『🔴 訊號日止蝕價』是主力的鐵底，收盤不破就死抱，安心讓 8 段長尾止盈去發揮威力！")
else:
    print("\n  > 📡 掃描完畢。今日全球市場無符合條件的標的，請耐心等待訊號。")

🚀 啟動【全球熊去牛來】實戰狙擊雷達 (嚴格錨定訊號日底線)...

⏳ 雷達全球掃描進度: [136/136] 處理中: 285A.T

==========================================================================================
🎯 【熊去牛來：全球跨市場實戰狙擊清單】
過濾防線：[收市跌穿訊號日低點] 判定出局 | 買入 <= 5天 | 偏離 <= 5%

,市場,標的,訊號觸發日,已過天數,最新收盤價,買入訊號價,現價偏離度(%),🔴 訊號日止蝕價,🛡️ 距止蝕風險(%)
0,🇺🇸 美股/加密貨幣,ARKK,2026-03-17,1,71.41,73.06,-2.26%,71.31,0.14%
1,🇺🇸 美股/加密貨幣,TSEM,2026-03-18,0,141.96,141.96,0.0%,133.66,5.85%
2,🇺🇸 美股/加密貨幣,LEU,2026-03-12,4,208.46,214.85,-2.97%,192.33,7.74%

💡 操盤建議：這份名單中的『🔴 訊號日止蝕價』是主力的鐵底，收盤不破就死抱，安心讓 8 段長尾止盈去發揮威力！

In [2]:
# ========== 熊去牛來：全球跨市場實戰狙擊雷達 (絕對防守鐵律版) ==========
!pip install pandas_ta -q
import yfinance as yf
import pandas as pd
import pandas_ta as ta
import numpy as np
import time
import sys
from datetime import datetime

# 👉 全球多資產監控清單
market_watch_lists = {
    "🇺🇸 美股與加密貨幣": [
        "AMD", "AMZN", "ARKG", "ARKK", "ARKX", "ARM", "ASTS", "ASX", "AVGO", "BABA", "BE",
        "AES", "AGX", "ALGN", "AMKR", "CAT", "CAVA", "DECK", "EME", "FIX", "FLEX", "MAR", "MRNA",
        "BLSH", "BTC-USD", "BULL", "BWXT", "CCJ", "CIEN", "COHR", "COIN", "CRWD", "CRWV",
        "DELL", "ENPH", "ESLT", "ETN", "FCX", "FUTU", "GEV", "GOOGL", "HOOD", "HSAI",
        "IBKR", "IONQ", "IREN", "ISRG", "JOBY", "KC", "KWEB", "KTOS", "LEU", "LITE", "MP",
        "MRVL", "MSFT", "MU", "NBIS", "NEM", "NET", "NVDA", "NXT", "ONDS", "ORCL", "OSCR",
        "OXY", "PANW", "PLTR", "RDDT", "RDW", "RKLB", "SATS", "SCCO", "SEDG", "SMCI",
        "SNPS", "SOFI", "STX", "SYM", "TEM", "TER", "TSLA", "TSM", "TSEM", "TTMI", "TXN",
        "VRT", "WDC", "WRD"
    ],
    "🇭🇰 香港股市": [
        "2722.HK", "2038.HK", "0902.HK", "0968.HK", "2727.HK", "0390.HK", "1157.HK", "1133.HK",
        "1428.HK", "1378.HK", "2208.HK", "9698.HK", "2026.HK", "2616.HK", "0981.HK", "3339.HK",
        "1729.HK", "1651.HK", "1050.HK", "9626.HK", "1286.HK", "2359.HK", "2252.HK", "2276.HK",
        "1772.HK", "9880.HK", "1057.HK", "9888.HK", "1816.HK", "6088.HK", "3750.HK", "9988.HK",
        "0700.HK", "1024.HK", "1801.HK", "2202.HK", "1918.HK", "2689.HK", "1579.HK", "1070.HK", "0388.HK"
    ],
    "🇯🇵 日本股市": [
        "8001.T", "8002.T", "8031.T", "8053.T", "8058.T", "285A.T"
    ]
}

watch_list = [sym for market in market_watch_lists.values() for sym in market]

print(f"🚀 啟動【全球熊去牛來】實戰雷達 (防守鐵律：收市跌穿訊號日低點)...\n")
scan_results = []
total_stocks = len(watch_list)
processed = 0

for sym in watch_list:
    processed += 1
    try:
        df = yf.Ticker(sym).history(period="6mo")
        if len(df) < 50: continue

        macd = df.ta.macd()
        df['MACD'] = macd.iloc[:, 0]
        df['MACD_Signal'] = macd.iloc[:, 2]
        df['Bear_Bull_Signal'] = (df['MACD'] > df['MACD_Signal']) & (df['MACD'].shift(1) <= df['MACD_Signal'].shift(1)) & (df['MACD'] < 0)

        status = "NONE"
        signal_idx, signal_high, rolling_high = -1, np.nan, np.nan

        # 🛡️ 鐵壁防禦變數：訊號發出日(Signal Day)的最低點
        signal_day_low = np.nan

        entry_price = np.nan
        entry_idx = -1
        entry_date = None

        for i in range(1, len(df)):
            current_date = df.index[i]
            current_close = df['Close'].iloc[i]
            current_open = df['Open'].iloc[i]
            current_high = df['High'].iloc[i]

            is_signal = df['Bear_Bull_Signal'].iloc[i]

            # 階段一：熊去牛來訊號發出日
            if status == "NONE":
                if is_signal:
                    status = "WAIT_CONFIRMATION"
                    signal_idx = i
                    signal_high = current_high
                    rolling_high = current_high
                    # 🎯 鎖定訊號日最低點！
                    signal_day_low = df['Low'].iloc[i]

            # 階段二：真正買入觸發日
            elif status == "WAIT_CONFIRMATION":
                days_passed = i - signal_idx
                if days_passed > 10:
                    status = "NONE"; continue

                triggered = False
                if days_passed == 1 and (current_close > current_open) and current_close > signal_high: triggered = True
                elif days_passed > 1 and current_close > rolling_high: triggered = True

                if triggered:
                    entry_price, entry_date, entry_idx = current_close, current_date, i
                    status = "HOLDING"
                    # 🎯 此處絕不覆寫 signal_day_low
                else:
                    if current_high > rolling_high: rolling_high = current_high

            # 階段三：持倉防守期
            elif status == "HOLDING":
                # 🎯 嚴格判定：收市價(current_close) 跌穿 訊號日低點(signal_day_low) 才出局
                if current_close < signal_day_low:
                    status = "NONE"

        # ==========================================
        # 🎯 雷達最後過濾 (顯示當下可以買的黃金標的)
        # ==========================================
        last_idx = len(df) - 1
        current_close = df['Close'].iloc[-1]

        if status == "HOLDING":
            days_since_entry = last_idx - entry_idx

            # 條件 1：買入不超過 5 天
            if days_since_entry <= 5:
                price_diff_pct = abs(current_close - entry_price) / entry_price * 100

                # 條件 2：現價偏離買入價 5% 以內
                if price_diff_pct <= 5.0:
                    sl_risk_pct = (current_close - signal_day_low) / current_close * 100

                    market_label = "🇺🇸 美股/加密貨幣"
                    if ".HK" in sym: market_label = "🇭🇰 港股"
                    elif ".T" in sym: market_label = "🇯🇵 日股"

                    scan_results.append({
                        "市場": market_label,
                        "標的": sym,
                        "買入觸發日": entry_date.strftime('%Y-%m-%d'),
                        "已過天數": days_since_entry,
                        "最新收市價": round(current_close, 2),
                        "買入觸發價": round(entry_price, 2),
                        "現價偏離度(%)": f"{round((current_close - entry_price) / entry_price * 100, 2)}%",
                        "🔴 訊號日止蝕價": round(signal_day_low, 2),
                        "🛡️ 距止蝕風險(%)": f"{round(sl_risk_pct, 2)}%"
                    })

        sys.stdout.write(f"\r⏳ 雷達全球掃描進度: [{processed}/{total_stocks}] 處理中: {sym}" + " "*15)
        sys.stdout.flush()
        time.sleep(0.05)
    except Exception as e: pass

# ========== 印出雷達狙擊報表 ==========
print("\n\n" + "="*90)
print("🎯 【熊去牛來：全球跨市場實戰狙擊清單】")
print("防禦鐵律：[收市價] 跌穿 [訊號發出日最低點] 判定出局")

if len(scan_results) > 0:
    res_df = pd.DataFrame(scan_results)
    res_df = res_df.sort_values(by='🛡️ 距止蝕風險(%)', key=lambda col: col.str.replace('%', '').astype(float)).reset_index(drop=True)
    display(res_df)
    print("\n💡 操盤建議：這份名單中的『🔴 訊號日止蝕價』就是主力的鐵底！只要每日收市價大於這個數字，就死抱著等待 8 段 ATR 的利潤噴發！")
else:
    print("\n  > 📡 掃描完畢。今日全球市場無符合條件的標的，請耐心等待黃金訊號。")

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.5/79.5 kB 3.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.0/62.0 kB 4.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 240.3/240.3 kB 10.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.9/3.9 MB 65.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.5/16.5 MB 73.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 59.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.4/42.4 MB 16.0 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 3.0.1 which is incompatible.
tensorflow 2.19.0 requires numpy<2.2.0,>=1.26.0, but you have numpy 2.2.6 which is incompatible.
bqplot 0.12.45 requires pandas<3.0.0,>=1.0.0, but you have pandas 3.0.1 which is incompatible.
db-dtypes 1.5.0 requires pandas<3.0.0,>=1.5.3, but you have pandas 3.0.1 which is incompatible.
gradio 5.50.0 requires pandas<3.0,>=1.0, but you have pandas 3.0.1 which is incompatible.
🚀 啟動【全球熊去牛來】實戰雷達 (防守鐵律：收市跌穿訊號日低點)...

⏳ 雷達全球掃描進度: [136/136] 處理中: 285A.T

==========================================================================================
🎯 【熊去牛來：全球跨市場實戰狙擊清單】
防禦鐵律：[收市價] 跌穿 [訊號發出日最低點] 判定出局

,市場,標的,買入觸發日,已過天數,最新收市價,買入觸發價,現價偏離度(%),🔴 訊號日止蝕價,🛡️ 距止蝕風險(%)
0,🇺🇸 美股/加密貨幣,ARKK,2026-03-17,1,71.41,73.06,-2.26%,71.31,0.14%
1,🇺🇸 美股/加密貨幣,TSEM,2026-03-18,0,141.96,141.96,0.0%,133.66,5.85%
2,🇺🇸 美股/加密貨幣,LEU,2026-03-12,4,208.46,214.85,-2.97%,192.33,7.74%

💡 操盤建議：這份名單中的『🔴 訊號日止蝕價』就是主力的鐵底！只要每日收市價大於這個數字，就死抱著等待 8 段 ATR 的利潤噴發！

In [7]:
# ========== 熊去牛來 (30日全景監控版 - 進階訊號與止蝕邏輯) ==========
import yfinance as yf
import pandas as pd
import pandas_ta as ta
import numpy as np
import time
from datetime import datetime, timedelta

market_watch_lists = {
    "🇺🇸 美股與加密貨幣": ["EWY", "GOOGL", "NVDA", "BTC-USD", "TSLA", "TSM", "AVGO", "GEV", "LITE", "MU", "NBIS", "NET", "ONDS", "PLTR", "NEM", "VRT", "AAOI", "ASTS", "BE", "CIEN", "COIN", "DELL", "ENPH", "HOOD", "IONQ", "KTOS", "LAC", "LEU", "MRVL", "MSFT", "NXT", "OSCR", "RKLB", "SEDG", "UMAC", "BLSH", "ACHR", "LASR", "AMTM", "IREN", "TSEM", "BWXT", "PL", "LMND", "CCJ", "MP", "AMD", "SOFI", "SYM", "ORCL", "ESLT", "UUUU", "HSAI", "KWEB", "WRD", "PONY", "FUTU"],
    "🇭🇰 香港股市": ["2722.HK", "2038.HK", "0902.HK", "0968.HK", "2727.HK", "0390.HK", "1157.HK", "1133.HK", "1428.HK", "1378.HK", "2208.HK", "9698.HK", "2026.HK", "2616.HK", "0981.HK", "3339.HK", "1729.HK", "1651.HK", "1050.HK", "9626.HK", "1286.HK", "2359.HK", "2252.HK", "2276.HK", "1772.HK", "9880.HK", "1057.HK", "9888.HK", "1816.HK", "6088.HK", "3750.HK", "9988.HK", "0700.HK", "1024.HK", "1801.HK", "2202.HK", "1918.HK", "2689.HK", "1579.HK", "1070.HK", "0388.HK"],
    "🇯🇵 日本股市": ["8001.T", "8002.T", "8031.T", "8053.T", "8058.T", "285A.T"]
}

RSI_OVERSOLD, VOL_RATIO, DEV_PERCENT = 30, 2.0, -5.0
print("🚀 開始執行【熊去牛來】30日進階監控 (區分訊號與買入、精準止蝕)...\n")
market_results = {k: [] for k in market_watch_lists.keys()}
today = datetime.now().astimezone()

for market_name, stock_list in market_watch_lists.items():
    print(f"\n📂 正在掃描 【{market_name}】")
    for sym in stock_list:
        try:
            df = yf.Ticker(sym).history(period="6mo")
            if df.empty or len(df) < 50: continue

            # 技術指標計算
            df['RSI'] = df.ta.rsi(length=14)
            df['Price_Low_10'] = df['Low'].rolling(10).min()
            df['RSI_Low_10'] = df['RSI'].rolling(10).min()
            df['Vol_MA_20'] = df.ta.sma(close=df['Volume'], length=20)
            df['EMA_20'] = df.ta.ema(length=20)
            macd = df.ta.macd(fast=12, slow=26, signal=9)
            macd_line = macd.iloc[:, 0]
            stoch = df.ta.stoch(k=14, d=3, smooth_k=1)

            # 訊號條件
            s1 = (df['RSI'] <= RSI_OVERSOLD) & ((df['Low'] <= df['Price_Low_10']) & (df['RSI'] > df['RSI_Low_10'] * 1.1)) & (df['Volume'] > df['Vol_MA_20'] * VOL_RATIO)
            body = abs(df['Close'] - df['Open'])
            lower_shadow = np.minimum(df['Open'], df['Close']) - df['Low']
            s2 = ((lower_shadow > body * 2) & ((df['High'] - np.maximum(df['Open'], df['Close'])) < body * 0.5)) & (df['Volume'] > df['Vol_MA_20'] * VOL_RATIO) & ((df['Low'] <= df.ta.bbands(length=20, std=2).iloc[:, 0]) & (df['Close'] > df.ta.bbands(length=20, std=2).iloc[:, 0]))
            s3 = (((df['Close'] - df['EMA_20']) / df['EMA_20'] * 100) < DEV_PERCENT) & ((df['Low'] <= df['Price_Low_10']) & (macd_line > macd_line.rolling(10).min() * 1.2)) & ((stoch.iloc[:, 0] < 20) & (stoch.iloc[:, 0] > stoch.iloc[:, 0].shift(1)) & (stoch.iloc[:, 0] > stoch.iloc[:, 1]))
            s4 = ((df['Low'] <= df['Price_Low_10']) & (df['RSI'] > df['RSI_Low_10'] * 1.1)) & ((df['Low'] <= df['Price_Low_10']) & (macd_line > macd_line.rolling(10).min() * 1.2)) & (df['Close'] > df['High'].shift(1).rolling(5).max())

            df['Signal_Day'] = s1 | s2 | s3 | s4

            # 狀態機追蹤變數
            trade_history = []
            signal_active, in_position = False, False
            signal_date, entry_date, sl_date = pd.NaT, pd.NaT, pd.NaT
            sl_price, entry_price, signal_high = np.nan, np.nan, np.nan

            for i in range(len(df)):
                current_date = df.index[i]
                current_close = df['Close'].iloc[i]
                current_low = df['Low'].iloc[i]
                current_high = df['High'].iloc[i]

                # 1. 檢查止蝕 (已買入狀態下，收盤價跌穿訊號日最低點)
                if in_position:
                    if current_close < sl_price:
                        in_position = False
                        signal_active = False
                        sl_date = current_date
                        trade_history.append({
                            "標的": sym, "狀態": "已止蝕", "訊號日": signal_date, "買入日": entry_date,
                            "止蝕日": sl_date, "買入價": entry_price, "止蝕價": sl_price
                        })
                        continue

                # 2. 檢查買入觸發 (有訊號但未買入，收盤價突破訊號日最高價)
                if signal_active and not in_position:
                    if current_close < sl_price:
                        # 未買入前就跌穿止蝕，訊號失效
                        signal_active = False
                    elif current_close > signal_high:
                        in_position = True
                        entry_date = current_date
                        entry_price = current_close

                # 3. 檢查新訊號 (可覆蓋舊有未觸發訊號)
                if df['Signal_Day'].iloc[i]:
                    signal_active = True
                    signal_date = current_date
                    sl_price = current_low    # 止蝕位 = 訊號日最低點
                    signal_high = current_high

            # 結算最後狀態
            if in_position:
                trade_history.append({"標的": sym, "狀態": "持倉中", "訊號日": signal_date, "買入日": entry_date, "止蝕日": pd.NaT, "買入價": entry_price, "止蝕價": sl_price})
            elif signal_active and not in_position:
                trade_history.append({"標的": sym, "狀態": "等待買入突破", "訊號日": signal_date, "買入日": pd.NaT, "止蝕日": pd.NaT, "買入價": np.nan, "止蝕價": sl_price})

            # 擷取該股票最近一次紀錄 (過濾 30 天內)
            if trade_history:
                last_trade = trade_history[-1]
                # 判定關聯日期是否在30天內
                check_date = last_trade['止蝕日'] if last_trade['狀態'] == "已止蝕" else last_trade['訊號日']
                if pd.notna(check_date) and (today - check_date).days <= 30:
                    current_price = df['Close'].iloc[-1]
                    dist_sl_pct = (current_price - last_trade['止蝕價']) / last_trade['止蝕價'] * 100

                    dist_entry_pct = np.nan
                    if pd.notna(last_trade['買入價']):
                        dist_entry_pct = (current_price - last_trade['買入價']) / last_trade['買入價'] * 100

                    # 狀態標記邏輯
                    status_str = last_trade['狀態']
                    if status_str == "已止蝕" and (today - last_trade['止蝕日']).days <= 5:
                        status_str = "🔴🔴🔴 近期止蝕"
                    elif status_str == "持倉中":
                        if 0 <= dist_sl_pct <= 4.0:
                            status_str = "💫💫💫 持倉中(極近止蝕防守區)"
                        elif pd.notna(dist_entry_pct) and 0 <= dist_entry_pct <= 4.0:
                            status_str = "💫 持倉中(剛起步)"

                    market_results[market_name].append({
                        "標的": sym,
                        "狀態": status_str,
                        "訊號日": last_trade['訊號日'].strftime('%Y-%m-%d') if pd.notna(last_trade['訊號日']) else "-",
                        "買入日": last_trade['買入日'].strftime('%Y-%m-%d') if pd.notna(last_trade['買入日']) else "-",
                        "買入價": round(last_trade['買入價'], 2) if pd.notna(last_trade['買入價']) else "-",
                        "距買入%": f"{dist_entry_pct:+.2f}%" if pd.notna(dist_entry_pct) else "-",
                        "止蝕價(訊號低點)": round(last_trade['止蝕價'], 2),
                        "距止蝕%": round(dist_sl_pct, 2),  # 保留數值以供排序
                        "現價": round(current_price, 2)
                    })

            import sys
            sys.stdout.write(f"\r  👉 已檢查: {sym} " + " "*10); sys.stdout.flush()
            time.sleep(0.5)
        except Exception as e: pass

print("\n" + "="*80)

# 顯示與排序邏輯
for market_name, results in market_results.items():
    print(f"\n📊 【{market_name}】 熊去牛來 30 日戰報 (依距止蝕%排序)：")
    if len(results) > 0:
        res_df = pd.DataFrame(results)

        # 建立排序權重: 1.持倉/等待買入 (0), 2.已止蝕 (1)
        res_df['Sort_Group'] = res_df['狀態'].apply(lambda x: 1 if "止蝕" in str(x) else 0)

        # 根據群組與距止蝕%升冪排序 (愈近止蝕排愈上面)
        res_df = res_df.sort_values(by=['Sort_Group', '距止蝕%'], ascending=[True, True]).reset_index(drop=True)

        # 格式化輸出
        res_df['距止蝕%'] = res_df['距止蝕%'].apply(lambda x: f"{x:+.2f}%" if pd.notna(x) else "-")
        res_df = res_df.drop(columns=['Sort_Group'])

        # 重排欄位順序以提升閱讀體驗
        cols = ['標的', '狀態', '訊號日', '買入日', '現價', '買入價', '距買入%', '止蝕價(訊號低點)', '距止蝕%']
        display(res_df[cols])
    else:
        print("  > 過去 30 天內無任何活動紀錄。")

🚀 開始執行【熊去牛來】30日進階監控 (區分訊號與買入、精準止蝕)...


📂 正在掃描 【🇺🇸 美股與加密貨幣】
  👉 已檢查: FUTU
📂 正在掃描 【🇭🇰 香港股市】
  👉 已檢查: 0388.HK
📂 正在掃描 【🇯🇵 日本股市】
  👉 已檢查: 285A.T
================================================================================

📊 【🇺🇸 美股與加密貨幣】 熊去牛來 30 日戰報 (依距止蝕%排序)：

,標的,狀態,訊號日,買入日,現價,買入價,距買入%,止蝕價(訊號低點),距止蝕%
0,ASTS,持倉中,2026-02-23,2025-11-24,90.74,55.00,+64.98%,77.90,+16.48%
1,LMND,持倉中,2026-02-24,2026-02-26,64.42,55.17,+16.77%,48.29,+33.40%
2,AMTM,已止蝕,2026-02-24,2026-03-02,27.07,30.70,-11.82%,29.16,-7.17%
3,SOFI,🔴🔴🔴 近期止蝕,2026-02-23,2026-02-25,17.18,19.29,-10.94%,17.58,-2.28%
4,SYM,已止蝕,2026-02-05,2026-02-03,50.06,56.12,-10.80%,50.87,-1.60%
5,ACHR,💫💫💫 持倉中(極近止蝕防守區),2026-03-16,2026-03-17,6.01,6.29,-4.45%,5.97,+0.75%
6,KWEB,💫💫💫 持倉中(極近止蝕防守區),2026-03-03,2026-03-04,29.45,29.99,-1.80%,29.11,+1.17%
7,MSFT,💫💫💫 持倉中(極近止蝕防守區),2026-02-24,2026-02-25,391.79,400.60,-2.20%,381.71,+2.64%
8,GOOGL,💫💫💫 持倉中(極近止蝕防守區),2026-02-17,2026-02-20,307.69,314.76,-2.25%,296.04,+3.93%

📊 【🇭🇰 香港股市】 熊去牛來 30 日戰報 (依距止蝕%排序)：

,標的,狀態,訊號日,買入日,現價,買入價,距買入%,止蝕價(訊號低點),距止蝕%
0,0700.HK,💫 持倉中(剛起步),2026-03-04,2026-03-06,520.50,519.00,+0.29%,498.80,+4.35%
1,9888.HK,💫 持倉中(剛起步),2026-03-04,2026-03-06,119.50,119.50,+0.00%,112.80,+5.94%
2,9626.HK,持倉中,2026-03-09,2026-03-10,200.60,205.60,-2.43%,187.20,+7.16%
3,1918.HK,持倉中,2026-03-04,2026-01-29,1.16,1.33,-12.78%,1.06,+9.43%
4,9698.HK,持倉中,2026-03-04,2025-11-20,44.44,30.10,+47.64%,35.50,+25.18%
5,2026.HK,已止蝕,2026-02-06,2026-02-09,86.70,109.70,-20.97%,100.20,-13.47%
6,1024.HK,🔴🔴🔴 近期止蝕,2026-03-04,2026-03-06,56.30,61.45,-8.38%,57.90,-2.76%
7,2202.HK,🔴🔴🔴 近期止蝕,2026-03-04,2026-03-06,3.31,3.49,-5.16%,3.35,-1.19%
8,9880.HK,💫💫💫 持倉中(極近止蝕防守區),2026-03-16,2026-03-18,102.20,105.60,-3.22%,99.05,+3.18%
9,0981.HK,💫💫💫 持倉中(極近止蝕防守區),2026-03-09,2026-03-10,60.20,64.20,-6.23%,58.30,+3.26%

📊 【🇯🇵 日本股市】 熊去牛來 30 日戰報 (依距止蝕%排序)：
  > 過去 30 天內無任何活動紀錄。